#DATA CLEANING

In [72]:
import pandas as pd
import numpy as np

pd.read_excel("../../01_Raw_Data/online_retail_II.xlsx").head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [73]:
import pandas as pd
import numpy as np

sheet_1 = pd.read_excel("../../01_Raw_Data/online_retail_II.xlsx",
              sheet_name= "Year 2009-2010")

sheet_2 = pd.read_excel("../../01_Raw_Data/online_retail_II.xlsx",
              sheet_name= "Year 2010-2011")

retail_df = pd.concat(
    [sheet_1, sheet_2],
    ignore_index= True
)

print(retail_df.shape)

(1067371, 8)

##MISSING VALUES

In [74]:
retail_df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [75]:
missing_values = pd.DataFrame({
    "Missing Values" :
    retail_df.isnull().sum(),
    "Percentage":
    round((retail_df.isnull().sum()/len(retail_df))*100,2)
})
missing_values

             Missing Values  Percentage
Invoice                   0        0.00
StockCode                 0        0.00
Description            4382        0.41
Quantity                  0        0.00
InvoiceDate               0        0.00
Price                     0        0.00
Customer ID          243007       22.77
Country                   0        0.00

##cUSTOMER ID MISSING ANALYSIS

In [76]:
retail_df[retail_df["Customer ID"].isnull()].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom

In [77]:
retail_df[retail_df["Customer ID"].isnull()].shape

(243007, 8)

In [78]:
retail_df[retail_df["Customer ID"].isnull()]["Invoice"].nunique()

8752

##DESCRIPTION MISSING ANALYSIS

In [79]:
retail_df[retail_df["Description"].isnull()].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

In [80]:
retail_df[retail_df["Description"].isnull()].shape

(4382, 8)

In [81]:
retail_df[retail_df["Description"].isnull()]["Invoice"].nunique()

4275

##DUPLICATE RECORDS ANALYSIS

In [82]:
retail_df.duplicated().sum()

np.int64(34335)

In [83]:
retail_df[retail_df.duplicated()].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom

In [84]:
retail_df[retail_df.duplicated()].shape

(34335, 8)

In [85]:
retail_df.duplicated().sum()

np.int64(34335)

In [86]:
retail_df= retail_df.drop_duplicates()
retail_df.shape

(1033036, 8)

In [87]:
retail_df.duplicated().sum()

np.int64(0)

In [88]:
retail_df[retail_df["Quantity"] <0].shape
retail_df[retail_df["Quantity"] <0].head()
retail_df[retail_df["Quantity"] <0]["Invoice"].nunique()

11684

In [89]:
retail_df[retail_df["Quantity"] <0] ["Invoice"].astype(str).head()

178    C489449
179    C489449
180    C489449
181    C489449
182    C489449
Name: Invoice, dtype: str

In [90]:
retail_df[ 
    retail_df["Invoice"].astype(str).str.startswith("C", na=False)
].shape

(19104, 8)

In [91]:
retail_df = retail_df[ 
    ~retail_df["Invoice"].astype(str).str.startswith("C", na=False)
]
retail_df.shape

(1013932, 8)

In [92]:
retail_df[ 
    retail_df["Invoice"].astype(str).str.startswith("C", na=False)
].shape

(0, 8)

In [93]:
retail_df.isnull().sum()

Invoice             0
StockCode           0
Description      4275
Quantity            0
InvoiceDate         0
Price               0
Customer ID    234437
Country             0
dtype: int64

In [94]:
retail_df = retail_df.dropna(subset=["Customer ID"])
retail_df.shape

(779495, 8)

In [95]:
retail_df   ["Customer ID"].isnull().sum()

np.int64(0)

In [96]:
retail_df[retail_df["Price"] <0].shape

(0, 8)

In [97]:
retail_df[retail_df["Price"] <0].head()

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [98]:
retail_df[retail_df["Price"] ==0].shape

(70, 8)

In [99]:
retail_df[retail_df["Price"] ==0].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126.0,United Kingdom
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658.0,United Kingdom
16107,490727,M,Manual,1,2009-12-07 16:38:00,0.0,17231.0,United Kingdom
18738,490961,22065,CHRISTMAS PUDDING TRINKET POT,1,2009-12-08 15:25:00,0.0,14108.0,United Kingdom
18739,490961,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-08 15:25:00,0.0,14108.0,United Kingdom

In [100]:
retail_df= retail_df[retail_df["Price"] > 0]
retail_df.shape

(779425, 8)

In [101]:
type(retail_df)

pandas.DataFrame

In [102]:
retail_df.shape

(779425, 8)

In [103]:
retail_df.to_csv(
    "../../02_Cleaned_Data/online_retail_cleaned.csv",
    index=False 
)

print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully

In [104]:
import os 
os.listdir("../../02_Cleaned_Data")

['online_retail_cleaned.csv']

# Data Cleaning Summary

## Objective
Prepare the dataset for reliable analytics and modeling.

## Key Findings
- Missing values were addressed.
- Duplicate records were removed.
- Data types were corrected.
- Dataset quality improved significantly.

## Recommendations
- Use cleaned dataset for all future analysis.
- Maintain data validation checks.
- Monitor data quality regularly.
- Document cleaning rules for future projects.